services:
  db:
    ports:
      - 5432:5432
    container_name: postgresql_container
    image: postgres
    environment:
      - POSTGRES_DB=sysFrete
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    expose:
      - 5432
    volumes:
      - C:\postgres_datapart:/var/lib/postgresql/data
    restart: always
  backend:
    build: .
    container_name: azship
    ports:
      - 8080:8080
    environment:
      db-url: jdbc:postgresql://db:5432/sysFrete
      db-username: postgres
      db-password: 123456
    depends_on:
      - db
    restart: always
